### ISSUE TITLE
Installing Elastix 4.0 on Amazon Centos7

### ISSUE THREAD

**Issue by erikbct** [thpryrchn/Elastix4onCentos7vz#1]
Anytime I use this script installing Elastix on AWS I am then locked out and are not able to do anything.

Any recommendations on what steps to take to install on Amazon EC2?

**Comment by erikbct** [comment]
Installed on Digital Ocean without any issues.

**Comment by thpryrchn** [comment]
Yea, I have never tried it on Amazon EC2. Which EC2 setup were you trying?

**Comment by erikbct** [comment]
I don't remember which AMI because I had tried many different AMI's. and after each failed attempted, I removed all the AMI's and installed on DO, which seems to be working correctly.
